### ISSUE TITLE
URLs with a space don't work

### ISSUE THREAD

**Issue by crypt0biwan** [Pixel-Map/historicalNFTs#7]
When navigating to the "detail" page of a project loading fails if the url contains a space (in other words the urlencoded %20).

For example:
* https://nftarchaeology.io/nft-details/curio%20cards
* https://nftarchaeology.io/nft-details/the%20lost%20robbies

Possible fix:
Remove spaces in the link to the detail page
* https://nftarchaeology.io/nft-details/curiocards
* https://nftarchaeology.io/nft-details/thelostrobbies

**Comment by kenerwin88** [comment]
Fixed, ty for the heads up!
